Add lambda to ship Cloudwatch logs to Opensearch
mattermost/mattermost-cloud-monitoring pull request #359
Opened 2021-11-03 15:15 UTC by stafot

Issue: MM-39482

#### Summary
Add lambda to ship Cloudwatch logs to Opensearch.
The first logs we need to expose are them from Aurora Postgres Clusters

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-39842

2021-11-03 15:15 UTC, mattermod commented
The files `.circleci/config.yml, lambda-functions/logs-to-opensearch/Makefile` are in the blocklist for external contributors. Hence, these changes are not tested by the CI pipeline active until the build is re-triggered by a core committer or the PR is merged. Please be careful when reviewing it.
/cc @mattermost/core-security @mattermost/core-build-engineers

2021-11-08 10:43 UTC, mattermod commented
The files `.circleci/config.yml, lambda-functions/logs-to-opensearch/Makefile` are in the blocklist for external contributors. Hence, these changes are not tested by the CI pipeline active until the build is re-triggered by a core committer or the PR is merged. Please be careful when reviewing it.
/cc @mattermost/core-security @mattermost/core-build-engineers

2021-11-08 11:05 UTC, koox00 approved these changes
JavaScript part looks good to me 💪 
Added some nitpicking comments about `let` vs `const` in some parts, but they absolutely don't affect functionality at all

2021-11-08 11:08 UTC, mattermod commented
The files `.circleci/config.yml, lambda-functions/logs-to-opensearch/Makefile` are in the blocklist for external contributors. Hence, these changes are not tested by the CI pipeline active until the build is re-triggered by a core committer or the PR is merged. Please be careful when reviewing it.
/cc @mattermost/core-security @mattermost/core-build-engineers

2021-11-08 11:08 UTC, mattermod commented
The files `.circleci/config.yml, lambda-functions/logs-to-opensearch/Makefile` are in the blocklist for external contributors. Hence, these changes are not tested by the CI pipeline active until the build is re-triggered by a core committer or the PR is merged. Please be careful when reviewing it.
/cc @mattermost/core-security @mattermost/core-build-engineers

2021-11-08 12:52 UTC, mattermod commented
The files `.circleci/config.yml, lambda-functions/logs-to-opensearch/Makefile` are in the blocklist for external contributors. Hence, these changes are not tested by the CI pipeline active until the build is re-triggered by a core committer or the PR is merged. Please be careful when reviewing it.
/cc @mattermost/core-security @mattermost/core-build-engineers

2021-11-08 13:05 UTC, spirosoik requested changes
few comments

2021-11-08 13:05 UTC, spirosoik commented on lambda-functions/logs-to-opensearch/index.js
> +const https = require('https');
I cannot say much here to be honest

2021-11-08 13:05 UTC, spirosoik commented on terraform/aws/modules/logs-to-opensearch/cloudwatch.tf
> +  evaluation_periods  = "1"
wondering if all these should configurable and just have default values

2021-11-08 13:05 UTC, spirosoik commented on terraform/aws/modules/logs-to-opensearch/iam.tf
> +            "Resource": "arn:aws:logs:*:*:*"
should we make it a bit more inclusive?

2021-11-08 13:05 UTC, spirosoik commented on terraform/aws/modules/logs-to-opensearch/variables.tf
> +variable "private_subnet_ids" {}
please add description to variables

2021-11-08 13:15 UTC, stafot commented on terraform/aws/modules/logs-to-opensearch/iam.tf
> +            "Resource": "arn:aws:logs:*:*:*"
You mean less?

2021-11-08 15:52 UTC, mattermod commented
The files `.circleci/config.yml, lambda-functions/logs-to-opensearch/Makefile` are in the blocklist for external contributors. Hence, these changes are not tested by the CI pipeline active until the build is re-triggered by a core committer or the PR is merged. Please be careful when reviewing it.
/cc @mattermost/core-security @mattermost/core-build-engineers

2021-11-08 16:01 UTC, spirosoik approved these changes

2021-11-09 08:24 UTC, merged