create iam role for github runners to access aws secrets manager
mattermost/mattermost-cloud-monitoring pull request #790
Opened 2024-12-07 19:49 UTC by angeloskyratzakos

#### Summary
create iam role for github runners to access aws secrets manager

#### Ticket Link
https://mattermost.atlassian.net/browse/CLD-8657

#### Release Note

```release-note
create iam role for github runners to access aws secrets manager
```

2024-12-11 14:29 UTC, andrleite submitted a review, later dismissed

2024-12-11 16:59 UTC, toninis commented on aws/github-runner/iam.tf
> +      },
The principal needs to be the role of the service account

2024-12-12 15:01 UTC, toninis requested changes
It needs some extra perms to work 😄

2024-12-12 15:01 UTC, toninis commented on aws/github-runner/iam.tf
> +        Action = "sts:AssumeRole"
```suggestion
          AWS = var.service_account_role_arn
        }
        Action = [
                "sts:TagSession",
                "sts:AssumeRole"
          ]
```

2024-12-12 17:13 UTC, toninis approved these changes

2024-12-13 09:11 UTC, stafot approved these changes
lgtm

2024-12-13 09:19 UTC, merged